#!/bin/bash

# Define the default Steam library path
DEFAULT_STEAMAPPS_PATH="${HOME}/.local/share/Steam/steamapps"

# Define an array of Steam library steamapps paths to search
# Add your additional library paths to this array
STEAMAPPS_PATHS=(
    "${DEFAULT_STEAMAPPS_PATH}"
    # <-- Add your custom path here (for example: "/run/media/data/SteamLibrary/steamapps" )
)

# Check if at least one of the defined Steam paths exists
found_steam_path=false
for steam_path in "${STEAMAPPS_PATHS[@]}"; do
    if [ -d "${steam_path}" ]; then
        found_steam_path=true
        break
    fi
done

if [ "$found_steam_path" = false ]; then
    printf "No Steam library paths found. Please check the STEAMAPPS_PATHS array in the script."
    exit 1
fi

# Build the find command arguments dynamically from the array
FIND_PATHS=""
for steam_path in "${STEAMAPPS_PATHS[@]}"; do
    if [ -d "${steam_path}" ]; then
        FIND_PATHS+=" \"${steam_path}\""
    fi
done

# Hold any given game name pattern in here
GAME_PATTERN=""
if [ $# -gt 0 ]; then
    GAME_PATTERN="$*"
fi
eval "find ${FIND_PATHS} -maxdepth 1 -name 'appmanifest_*.acf' -print0" | while IFS= read -r -d '' file; do
    from_path=$(echo "$file" | sed 's#/appmanifest.*##')
    appid=$(basename "$file" | sed 's/appmanifest_\(.*\)\.acf/\1/')
    game_name=$(grep -Po '"name"\s+"\K[^"]+' "$file")
    if [ -n "$game_name" ]; then
        if [ $# -gt 0 ]; then
            # Parameter provided, filter by game name pattern
            if [[ "${game_name,,}" =~ ${GAME_PATTERN,,} ]]; then
                printf "Compatdata Folder: $appid -> Game: $game_name -> $from_path \n"
            fi
        else
        # No parameter provided, list all games and compatdata folders
            printf "Compatdata Folder: $appid -> Game: $game_name -> $from_path \n"
        fi
    fi
done | sort -V
